### ISSUE TITLE
Sean Todo - Mar 22

### ISSUE THREAD

**Issue by CTOverton** [CTOverton/CMPSC_488#35]
### User settings
- [x] Fix current issue with packages
- [ ] Implement options to change other attributes
- [ ] Implement user password confirmation for change
- [ ] Possibly implement changing multiple user attributes at once

### Weather API
- [ ] Implement Weather UI
