### ISSUE TITLE
Sam Todo - Mar 22

### ISSUE THREAD

**Issue by CTOverton** [CTOverton/CMPSC_488#36]
- [x] Fix bug where AttendeeDetails page does not load tags on reload
- [ ] Implement Filter for AttendeeList
- [ ] Implement Deleting Tags
- [ ] Design Decision => Implement Fake Deleting, or Na's Tag Collection with Users Approach
