### ISSUE TITLE
Christian Todo - Mar 22

### ISSUE THREAD

**Issue by CTOverton** [CTOverton/CMPSC_488#37]
- [ ] Event Signup Page
- [ ] Signup form
- [ ] Waitlist
- [x] Fix bottom nav links
- [x] Fix Login Forms Enter to submit
- [x] Update header to work with various screens
