### ISSUE TITLE
Todo Deliverable 7 

### ISSUE THREAD

**Issue by CTOverton** [CTOverton/CMPSC_488#38]
- [ ] Create Todo List @CTOverton 
- [x] Create Todo List @ATrulyRandomGuy  
- [x] Create Todo List @seanpmcn
